carthage_bootstrap:
	(cd Vendor && carthage bootstrap --use-xcframeworks --platform iOS --cache-builds)
	rm -rf Vendor/Carthage/Checkouts

carthage_update:
	(cd Vendor && carthage update --use-xcframeworks --platform iOS --cache-builds)
	rm -rf Vendor/Carthage/Checkouts

